name: Pull Request Actions

on:
    pull_request:
        branches: [master]

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: npm install
            - name: Versions used
              run: npm run version
            - name: Lint
              run: npm run lint
            - name: Build
              run: npm run build
            - name: Test + coverage
              run: npm run cover:ci
