name: Pull Request Actions

on:
    pull_request:
        branches: [master]

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: npm install
            - name: Lint
              run: npm run lint
            - name: tsc version
              run: tsc --version
            - name: npx tsc version
              run: npx tsc --version
            - name: Build mjs
              run: npm run build:mjs
            - name: Build cjs
              run: npm run build:cjs
            - name: Test + coverage
              run: npm run cover:ci
